/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.GestionEquipe.vue;

import Com.GestionEquipe.Metier.Membre;
import Com.GestionEquipe.Metier.Tache;
import Com.GestionEquipe.Metier.Tachemembre;
import Com.GestionEquipe.controler.ServiceIlocal;
import Com.GestionEquipe.controler.ServiceImpl;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author delus-jean-nelka
 */
public class AssignertacheFR extends javax.swing.JInternalFrame {
    ServiceIlocal se= new ServiceImpl();
    Tachemembre tachm=new Tachemembre();
    List<Membre>listemembre=new ArrayList<>();
     List<Tache>listetache=new ArrayList<>();
    /**
     * Creates new form AssignertacheFR
     */
    public AssignertacheFR() {
        initComponents();
    }
public void nettoyerChamps()
            {
            txtdesc.setText("");
            txtnomplet.setText("");
            }
        public void remplircombo()
        {
            listemembre=se.ListerMembre();
            listemembre.forEach((item) -> {
                cmbidmembre.addItem(""+item.getId());
        });
            listetache=se.ListerTache();
             listetache.forEach((item) -> {
                cmbidtache.addItem(""+item.getId());
        });
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbidmembre = new javax.swing.JComboBox<>();
        cmbidtache = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnomplet = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnassigner = new javax.swing.JButton();
        btnannuler = new javax.swing.JButton();

        setClosable(true);
        setTitle("Assigner Tache");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        cmbidmembre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbidmembreItemStateChanged(evt);
            }
        });
        cmbidmembre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbidmembreMouseClicked(evt);
            }
        });

        cmbidtache.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbidtacheItemStateChanged(evt);
            }
        });
        cmbidtache.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbidtacheMouseClicked(evt);
            }
        });

        jLabel1.setText("ID Membre");

        jLabel2.setText("ID Tache");

        jLabel3.setText("Nom complet");

        txtnomplet.setEnabled(false);

        txtdesc.setEnabled(false);

        jLabel4.setText("Description");

        btnassigner.setText("Assigner");
        btnassigner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnassignerActionPerformed(evt);
            }
        });

        btnannuler.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(txtnomplet, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnassigner, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                            .addComponent(btnannuler, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbidmembre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbidtache, 0, 148, Short.MAX_VALUE)
                                .addComponent(txtdesc)))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbidmembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnomplet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbidtache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnassigner)
                    .addComponent(btnannuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnassignerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnassignerActionPerformed
        // TODO add your handling code here:
        Random rnd=new Random();
        int id=rnd.nextInt(9999);
        tachm.setIdtachmembre(id);
        tachm.setMembreid(new Integer(cmbidmembre.getSelectedItem().toString()));
        tachm.setTacheid(new Integer(cmbidtache.getSelectedItem().toString()));
        String rep=se.AjouterTachemembre(tachm);
        JOptionPane.showMessageDialog(this, rep);
        nettoyerChamps();
    }//GEN-LAST:event_btnassignerActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        remplircombo();
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmbidmembreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbidmembreMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_cmbidmembreMouseClicked

    private void cmbidtacheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbidtacheMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbidtacheMouseClicked

    private void cmbidtacheItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbidtacheItemStateChanged
        // TODO add your handling code here:
         Tache tach=se.RechercherTache(new Integer(cmbidtache.getSelectedItem().toString()));
        txtdesc.setText(tach.getDescription());
    }//GEN-LAST:event_cmbidtacheItemStateChanged

    private void cmbidmembreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbidmembreItemStateChanged
        // TODO add your handling code here:
           Membre memb=se.RechercherMembre(new Integer(cmbidmembre.getSelectedItem().toString()));
        txtnomplet.setText(memb.getNom()+" "+memb.getPrenom());
    }//GEN-LAST:event_cmbidmembreItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnannuler;
    private javax.swing.JButton btnassigner;
    private javax.swing.JComboBox<String> cmbidmembre;
    private javax.swing.JComboBox<String> cmbidtache;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtnomplet;
    // End of variables declaration//GEN-END:variables
}
