/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.GestionEquipe.vue;

import Com.GestionEquipe.Metier.Tache;
import Com.GestionEquipe.controler.ServiceIlocal;
import Com.GestionEquipe.controler.ServiceImpl;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author delus-jean-nelka
 */
public class frmTache extends javax.swing.JInternalFrame {
ServiceIlocal se= new ServiceImpl();
   Tache tache=new Tache();
    List<Tache>listetache=new ArrayList<>();
    int index;
    TableModel mode;
    /**
     * Creates new form frmTache
     */
    public frmTache() {
        initComponents();
    }
public void nettoyerChamps()
            {
            txtDescriptiontache.setText("");
           txtetat.setText("");
            txtIdtache.setText("");
            txtNomtache.setText("");
            dtcdatedebut.setDate(null);
            dtcdatefin.setDate(null);
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdtache = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomtache = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescriptiontache = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dtcdatefin = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        dtcdatedebut = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTache = new javax.swing.JTable();
        btAjouter = new javax.swing.JButton();
        btRechercher = new javax.swing.JButton();
        btModifier = new javax.swing.JButton();
        btSupprimer = new javax.swing.JButton();
        txtetat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Tache");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("ID:");

        txtIdtache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdtacheActionPerformed(evt);
            }
        });

        jLabel2.setText("NOM:");

        txtNomtache.setText(" ");

        jLabel3.setText("DESCRIPTION:");

        txtDescriptiontache.setText(" ");

        jLabel4.setText("DATE DE DEBUT:");

        dtcdatefin.setDateFormatString("yyyy-MM-dd");

        jLabel5.setText("DATE DE DEBUT:");

        dtcdatedebut.setDateFormatString("yyyy-MM-dd");

        tableTache.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM", "DESCRIPTION", "DATE DEBUT", "DATE FIN", "Etat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableTache.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTacheMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTache);

        btAjouter.setText("AJOUTER");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        btRechercher.setText("RECHERCHER");
        btRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechercherActionPerformed(evt);
            }
        });

        btModifier.setText("MODIFIER");
        btModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierActionPerformed(evt);
            }
        });

        btSupprimer.setText("SUPPRIMER");
        btSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerActionPerformed(evt);
            }
        });

        txtetat.setText(" ");

        jLabel6.setText("Etat :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdtache, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescriptiontache, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomtache, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dtcdatefin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtetat, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtcdatedebut, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdtache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addComponent(dtcdatedebut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtNomtache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(dtcdatefin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAjouter)
                            .addComponent(btModifier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRechercher)
                            .addComponent(btSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescriptiontache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtetat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdtacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdtacheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdtacheActionPerformed

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        // TODO add your handling code here:
         if(txtIdtache.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Saisir l'ID du membre");}
        else
        {
        java.util.Date	dateDebut=dtcdatedebut.getDate();
     Date datedeb_sql= new java.sql.Date(dateDebut.getTime());
      String  datedeb =datedeb_sql.toString();
        ////////////////////date fin
       java.util.Date  dateFin= dtcdatefin.getDate();
       Date datefin_sql= new java.sql.Date(dateFin.getTime());
         String datefin =datefin_sql.toString();
         int id = new Integer(txtIdtache.getText());
          tache.setId(id);
        tache.setNom(txtNomtache.getText());
        tache.setDescription(txtDescriptiontache.getText());
        tache.setEtat(txtetat.getText());
        tache.setDatedebut(datedeb);
        tache.setDatefin(datefin);
        String rep=se.AjouterTache(tache);
        JOptionPane.showMessageDialog(this, rep);
        nettoyerChamps();
        listerTache();
        }
    }//GEN-LAST:event_btAjouterActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        listerTache();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tableTacheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTacheMouseClicked
        // TODO add your handling code here:
        index = tableTache.getSelectedRow();
     this.mode = tableTache.getModel();
    }//GEN-LAST:event_tableTacheMouseClicked

    private void btRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechercherActionPerformed
    try {
        // TODO add your handling code here:
        SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date dated=format.parse(mode.getValueAt(index, 3).toString());
        java.util.Date datef=format.parse(mode.getValueAt(index, 4).toString());
        Date datedeb_sql= new java.sql.Date(dated.getTime());
        Date datefin_sql= new java.sql.Date(datef.getTime());
        txtIdtache.setText(mode.getValueAt(index, 0).toString());
        txtNomtache.setText(mode.getValueAt(index, 1).toString());
        txtDescriptiontache.setText(mode.getValueAt(index, 2).toString());
        txtetat.setText(mode.getValueAt(index, 5).toString());
        dtcdatedebut.setDate(datedeb_sql);
        dtcdatefin.setDate(datefin_sql);
    } catch (ParseException ex) {
        Logger.getLogger(frmTache.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btRechercherActionPerformed

    private void btModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierActionPerformed
        // TODO add your handling code here:
        
         if(txtIdtache.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Saisir l'ID du membre");}
        else
        {
        java.util.Date	dateDebut=dtcdatedebut.getDate();
     Date datedeb_sql= new java.sql.Date(dateDebut.getTime());
      String  datedeb =datedeb_sql.toString();
        ////////////////////date fin
       java.util.Date  dateFin= dtcdatefin.getDate();
       Date datefin_sql= new java.sql.Date(dateFin.getTime());
         String datefin =datefin_sql.toString();
         int id = new Integer(txtIdtache.getText());
          tache.setId(id);
        tache.setNom(txtNomtache.getText());
        tache.setDescription(txtDescriptiontache.getText());
        tache.setEtat(txtetat.getText());
        tache.setDatedebut(datedeb);
        tache.setDatefin(datefin);
        String rep=se.ModifierTache(tache);
        JOptionPane.showMessageDialog(this, rep);
        nettoyerChamps();
        listerTache();
        }
    }//GEN-LAST:event_btModifierActionPerformed

    private void btSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerActionPerformed
        // TODO add your handling code here:
        int id = new Integer(txtIdtache.getText());
         String rep=se.SupprimerTache(id);
        JOptionPane.showMessageDialog(this, rep);
        nettoyerChamps();
        listerTache();
    }//GEN-LAST:event_btSupprimerActionPerformed
public void listerTache()
{
    listetache=se.ListerTache();
		          DefaultTableModel model= (DefaultTableModel) tableTache.getModel();
		  model.setRowCount(0);
		 Object[]data=new Object[6] ;
		 for(int i=0;i<listetache.size();i++) 
		 {
			 data[0]=listetache.get(i).getId();
			 data[1]=listetache.get(i).getNom();
			 data[2]=listetache.get(i).getDescription();
			 data[3]=listetache.get(i).getDatedebut();
			 data[4]=listetache.get(i).getDatefin();
			 data[5]=listetache.get(i).getEtat();
			 model.addRow(data);
			  
		 }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btModifier;
    private javax.swing.JButton btRechercher;
    private javax.swing.JButton btSupprimer;
    private com.toedter.calendar.JDateChooser dtcdatedebut;
    private com.toedter.calendar.JDateChooser dtcdatefin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTache;
    private javax.swing.JTextField txtDescriptiontache;
    private javax.swing.JTextField txtIdtache;
    private javax.swing.JTextField txtNomtache;
    private javax.swing.JTextField txtetat;
    // End of variables declaration//GEN-END:variables
}
