/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.GestionEquipe.vue;

import Com.GestionEquipe.Metier.Tache;
import Com.GestionEquipe.controler.ServiceIlocal;
import Com.GestionEquipe.controler.ServiceImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author delus-jean-nelka
 */
public class ListertacheFr extends javax.swing.JInternalFrame {
Tache tache=new Tache();
    List<Tache>listetache=new ArrayList<>();
    ServiceIlocal se= new ServiceImpl();
    /**
     * Creates new form ListertacheFr
     */
    public ListertacheFr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtrechercher = new javax.swing.JTextField();
        btnrecherche = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblistache = new javax.swing.JTable();

        setClosable(true);
        setTitle("Liste des taches");

        jLabel1.setText("Saisir ID");

        btnrecherche.setText("Rechercher");
        btnrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercheActionPerformed(evt);
            }
        });

        tblistache.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID tache", "Nom", "Description", "Date debut", "Date fin", "Etat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblistache);
        if (tblistache.getColumnModel().getColumnCount() > 0) {
            tblistache.getColumnModel().getColumn(0).setResizable(false);
            tblistache.getColumnModel().getColumn(1).setResizable(false);
            tblistache.getColumnModel().getColumn(2).setResizable(false);
            tblistache.getColumnModel().getColumn(3).setResizable(false);
            tblistache.getColumnModel().getColumn(4).setResizable(false);
            tblistache.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(txtrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrecherche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercheActionPerformed
        // TODO add your handling code here:
        if(txtrechercher.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Saisir l'ID du membre");}
        else
        {
        listerTache();
        }
    }//GEN-LAST:event_btnrechercheActionPerformed
public void listerTache()
{
    listetache=se.ListerTachemembre(new Integer(txtrechercher.getText()));
		          DefaultTableModel model= (DefaultTableModel) tblistache.getModel();
		  model.setRowCount(0);
		 Object[]data=new Object[6] ;
		 for(int i=0;i<listetache.size();i++) 
		 {
			 data[0]=listetache.get(i).getId();
			 data[1]=listetache.get(i).getNom();
			 data[2]=listetache.get(i).getDescription();
			 data[3]=listetache.get(i).getDatedebut();
			 data[4]=listetache.get(i).getDatefin();
			 data[5]=listetache.get(i).getEtat();
			 model.addRow(data);
			  
		 }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrecherche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblistache;
    private javax.swing.JTextField txtrechercher;
    // End of variables declaration//GEN-END:variables
}
