/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.GestionEquipe.vue;

/**
 *
 * @author delus-jean-nelka
 */
public class MainFR extends javax.swing.JFrame {

    /**
     * Creates new form MainFR
     */
    public MainFR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        smnnouveaumembre = new javax.swing.JMenuItem();
        smnlistertache = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        smncreertache = new javax.swing.JMenuItem();
        smnAssigner = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Membre");

        smnnouveaumembre.setText("Nouveau membre");
        smnnouveaumembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnnouveaumembreActionPerformed(evt);
            }
        });
        jMenu1.add(smnnouveaumembre);

        smnlistertache.setText("Lister tache");
        smnlistertache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnlistertacheActionPerformed(evt);
            }
        });
        jMenu1.add(smnlistertache);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tache");

        smncreertache.setText("Creer tache");
        smncreertache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smncreertacheActionPerformed(evt);
            }
        });
        jMenu2.add(smncreertache);

        smnAssigner.setText("Assigner tacher");
        smnAssigner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnAssignerActionPerformed(evt);
            }
        });
        jMenu2.add(smnAssigner);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnnouveaumembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnnouveaumembreActionPerformed
        // TODO add your handling code here:
        NouveauMembreFR nmf=new NouveauMembreFR();
        Desktop.add(nmf);
        nmf.show();
    }//GEN-LAST:event_smnnouveaumembreActionPerformed

    private void smncreertacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smncreertacheActionPerformed
        // TODO add your handling code here:
       frmTache nmf=new frmTache();
        Desktop.add(nmf);
        nmf.show();
    }//GEN-LAST:event_smncreertacheActionPerformed

    private void smnAssignerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnAssignerActionPerformed
        // TODO add your handling code here:
          AssignertacheFR atf=new AssignertacheFR();
        Desktop.add(atf);
        atf.show();
    }//GEN-LAST:event_smnAssignerActionPerformed

    private void smnlistertacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnlistertacheActionPerformed
        // TODO add your handling code here:
          ListertacheFr ltf=new ListertacheFr();
        Desktop.add(ltf);
        ltf.show();
    }//GEN-LAST:event_smnlistertacheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem smnAssigner;
    private javax.swing.JMenuItem smncreertache;
    private javax.swing.JMenuItem smnlistertache;
    private javax.swing.JMenuItem smnnouveaumembre;
    // End of variables declaration//GEN-END:variables
}
